# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(517, 243)
        main_window.setStyleSheet("background-color: #101820;\n"
"color: white;")
        self.centralwidget = QtWidgets.QWidget(main_window)
        self.centralwidget.setObjectName("centralwidget")
        self.download_v = QtWidgets.QPushButton(self.centralwidget)
        self.download_v.setGeometry(QtCore.QRect(150, 160, 150, 35))
        self.download_v.setStyleSheet("color: rgb(0, 0, 0);\n"
"border: 2px solid black;\n"
"border-radius: 15px;\n"
"background-color: rgb(250, 157, 16);")
        self.download_v.setObjectName("download_v")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 60, 30))
        self.label_2.setStyleSheet("color: white;")
        self.label_2.setObjectName("label_2")
        self.chifr = QtWidgets.QTextEdit(self.centralwidget)
        self.chifr.setGeometry(QtCore.QRect(140, 70, 311, 30))
        self.chifr.setStyleSheet("color: rgb(0, 0, 0);\n"
"border-radius: 10px;\n"
"border: 2px solid black;\n"
"background-color: rgb(226, 226, 226);")
        self.chifr.setObjectName("chifr")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 110, 121, 30))
        self.label_3.setStyleSheet("color: white;")
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 341, 21))
        font = QtGui.QFont()
        font.setFamily("Eras Demi ITC")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("color: white;\n"
"font: 15pt \"Eras Demi ITC\";")
        self.label.setObjectName("label")
        self.name_pd = QtWidgets.QTextEdit(self.centralwidget)
        self.name_pd.setGeometry(QtCore.QRect(140, 110, 311, 30))
        self.name_pd.setStyleSheet("color: rgb(0, 0, 0);\n"
"border-radius: 10px;\n"
"border: 2px solid black;\n"
"background-color: rgb(226, 226, 226);")
        self.name_pd.setObjectName("name_pd")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(460, -10, 121, 91))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("../logo.png"))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 170, 121, 16))
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        main_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(main_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 517, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        main_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(main_window)
        self.statusbar.setObjectName("statusbar")
        main_window.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(main_window)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(main_window)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(main_window)
        self.action_3.setObjectName("action_3")
        self.action_5 = QtWidgets.QAction(main_window)
        self.action_5.setObjectName("action_5")
        self.menu.addAction(self.action_5)
        self.menu_2.addAction(self.action_2)
        self.menu_2.addAction(self.action_3)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(main_window)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "АСВР"))
        self.download_v.setText(_translate("main_window", "Сформировать отчет"))
        self.label_2.setText(_translate("main_window", "Шифр ПД"))
        self.chifr.setHtml(_translate("main_window", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_3.setText(_translate("main_window", "Наименование объекта "))
        self.label.setText(_translate("main_window", "Анализ сводной ведомости ресурсов"))
        self.menu.setTitle(_translate("main_window", "Файл"))
        self.menu_2.setTitle(_translate("main_window", "Свойства"))
        self.action.setText(_translate("main_window", "Открыть..."))
        self.action_2.setText(_translate("main_window", "Настройки"))
        self.action_3.setText(_translate("main_window", "Справка"))
        self.action_5.setText(_translate("main_window", "Открыть..."))
